version: '2'

services:
    flask-app:
        container_name: flask-app
        build: ./flaskr
        restart: always
        ports:
            - '5000:5000'
        networks:
            - backend
        links: 
            - mysql-db

    mysql-db:
        container_name: mysql-db
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DB}
        ports:
            - '3308:3306'
        volumes:
            - ./database:/var/lib/mysql
        networks:
            - backend

networks:
    backend:

volumes:
    app:
    database:
